### PR TITLE
feat：修改首页svg版本号

### PR DESCRIPTION
**Pull request by xzkxzk123**
修改首页svg版本号

### CODE REVIEW

**Review by gaoxueyu — CHANGES_REQUESTED** [review]
please remove dist/docusaurus.config.dev.js file

**Comment by balinorLiang** [comment]
Author doesn't do change requested, so this PR should be closed, the change is in #111 now

**Comment by balinorLiang** [comment]
I think we could close this PR, because of no response from author. I created a new PR for this feature. #111 @gaoxueyu

**Comment by balinorLiang** [comment]
The file named [docusaurus.config.dev.js](https://github.com/IvorySQL/Ivory-www/pull/110/commits/b18bf74f355c9d71c6fb30f6e737c30161a22e75) has been deleted in a new commit. Please approve and do squash and merge. Thanks a lot. @gaoxueyu

**Review by gaoxueyu — APPROVED** [review]

**Comment by gaoxueyu** [comment]
approved

**Pull request merged**
